In [31]:
import requests

# Define the API endpoint
api_url = "https://live.markethound.in/api/history/expiries?index=NIFTY"

# Send GET request to the API
response = requests.get(api_url)

# Check for successful response
if response.status_code == 200:
  # Parse the JSON response
  data = response.json()

  # Access the expiry dates
  expiry_dates = data["result"]

  # Print the expiry dates
  print("Expiry Dates for FINNIFTY:")
  for expiry in expiry_dates:
    print(expiry)
else:
  print(f"Error: API request failed with status code {response.status_code}")

Expiry Dates for FINNIFTY:
2024-03-14T00:00:00.000Z
2024-03-07T00:00:00.000Z
2024-02-29T00:00:00.000Z
2024-02-22T00:00:00.000Z
2024-02-15T00:00:00.000Z
2024-02-08T00:00:00.000Z
2024-02-01T00:00:00.000Z
2024-01-25T00:00:00.000Z
2024-01-18T00:00:00.000Z
2024-01-11T00:00:00.000Z
2024-01-04T00:00:00.000Z
2023-12-28T00:00:00.000Z
2023-12-21T00:00:00.000Z
2023-12-14T00:00:00.000Z
2023-12-07T00:00:00.000Z
2023-11-30T00:00:00.000Z
2023-11-23T00:00:00.000Z
2023-11-16T00:00:00.000Z
2023-11-09T00:00:00.000Z
2023-11-02T00:00:00.000Z
2023-10-26T00:00:00.000Z
2023-10-19T00:00:00.000Z
2023-10-12T00:00:00.000Z
2023-10-05T00:00:00.000Z
2023-09-28T00:00:00.000Z
2023-09-21T00:00:00.000Z
2023-09-14T00:00:00.000Z
2023-09-07T00:00:00.000Z
2023-08-31T00:00:00.000Z
2023-08-24T00:00:00.000Z
2023-08-17T00:00:00.000Z
2023-08-10T00:00:00.000Z
2023-08-03T00:00:00.000Z
2023-07-27T00:00:00.000Z
2023-07-20T00:00:00.000Z

In [49]:
import pandas as pd

data_list1 = []

# iterating over all expiry dates
for expiry_date in expiry_dates:
  # collecting date from 0 to 4 only
  for dte in range(0,5):
   # Define the API endpoint
   api_url = f"https://live.markethound.in/api/history/decay?name=NIFTY&expiry={expiry_date}&dte={dte}"

   # Send GET request to the API
   response = requests.get(api_url)

   # Check for successful response
   if response.status_code == 200:
     # Parse the JSON response
     data = response.json()

     # Access the expiry dates
     results = data["result"]

     if results:
       # Create a list of dictionaries to store data
       # appending 1st element only because all other elements are of other expiry dates so they will be repeated if we take all of results
       data_list1.append(results[0])

   else:
     print(f"Error: API request failed with status code {response.status_code}")

# Create the DataFrame
df = pd.DataFrame(data_list1)

df

,_id,daysToExpiry,expiry,index,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,65f2e9b5301dfda3b6b521fd,0,2024-03-14T00:00:00.000Z,NIFTY,3.40,2024-03-14T00:00:00.000Z,156.80,22144.95,22201.90,21928.65,21956.00,273.25,141.20,2.70,144.60,0,0
1,65f2e9b5301dfda3b6b5220a,1,2024-03-14T00:00:00.000Z,NIFTY,151.35,2024-03-13T00:00:00.000Z,224.55,21984.20,22411.65,21909.55,22403.05,502.10,36.30,151.35,187.65,6.75,28.20
2,65f2e9b5301dfda3b6b5221c,2,2024-03-14T00:00:00.000Z,NIFTY,198.55,2024-03-12T00:00:00.000Z,233.15,22335.65,22450.70,22261.40,22341.65,189.30,22.15,195.25,220.70,10.90,-67.40
3,65f2e9b5301dfda3b6b5222f,3,2024-03-14T00:00:00.000Z,NIFTY,230.55,2024-03-11T00:00:00.000Z,260.85,22325.40,22511.00,22311.20,22486.95,199.80,30.30,230.55,260.85,9.85,-16.25
4,65f2e9b5301dfda3b6b5223d,4,2024-03-14T00:00:00.000Z,NIFTY,254.45,2024-03-07T00:00:00.000Z,314.10,22483.60,22519.60,22439.20,22498.05,80.40,59.65,247.95,314.10,-6.40,-3.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,6500482a50132f5a00c71af7,3,2023-07-27T00:00:00.000Z,NIFTY,173.05,2023-07-24T00:00:00.000Z,212.20,19663.65,19781.45,19663.65,19729.35,117.80,39.15,173.05,212.20,2.40,-34.10
169,6500482a50132f5a00c71b23,4,2023-07-27T00:00:00.000Z,NIFTY,215.80,2023-07-21T00:00:00.000Z,237.80,19772.00,19885.90,19709.10,19797.10,176.80,13.20,211.45,229.00,3.60,42.65
170,6500482450132f5a00c711cb,0,2023-07-20T00:00:00.000Z,NIFTY,20.10,2023-07-20T00:00:00.000Z,95.10,19967.70,19989.90,19759.65,19831.10,230.25,74.90,15.80,95.00,0,0
171,6500482450132f5a00c711fb,1,2023-07-20T00:00:00.000Z,NIFTY,94.65,2023-07-19T00:00:00.000Z,127.50,19839.55,19841.60,19730.65,19837.75,110.95,32.25,94.30,126.90,-0.35,8.45
172,6500482450132f5a00c71225,2,2023-07-20T00:00:00.000Z,NIFTY,133.40,2023-07-18T00:00:00.000Z,163.95,19744.35,19813.20,19692.45,19771.40,120.75,23.45,133.40,156.85,6.50,-93.40

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   daysToExpiry       167 non-null    int64
 1   close              167 non-null    object
 2   date               167 non-null    object
 3   high               167 non-null    object
 4   index_close        167 non-null    object
 5   index_high         167 non-null    object
 6   index_low          167 non-null    object
 7   index_open         167 non-null    object
 8   intradayMovement   167 non-null    object
 9   intradayTotal      167 non-null    object
 10  low                167 non-null    object
 11  open               167 non-null    object
 12  overnightExpected  167 non-null    object
 13  overnightGap       167 non-null    object
dtypes: int64(1), object(13)
memory usage: 18.4+ KB

In [50]:
# dropping the following columns, they are not relavant
df_dropped = df.drop(columns=['_id', 'index', 'expiry'])
df_dropped

,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,0,3.40,2024-03-14T00:00:00.000Z,156.80,22144.95,22201.90,21928.65,21956.00,273.25,141.20,2.70,144.60,0,0
1,1,151.35,2024-03-13T00:00:00.000Z,224.55,21984.20,22411.65,21909.55,22403.05,502.10,36.30,151.35,187.65,6.75,28.20
2,2,198.55,2024-03-12T00:00:00.000Z,233.15,22335.65,22450.70,22261.40,22341.65,189.30,22.15,195.25,220.70,10.90,-67.40
3,3,230.55,2024-03-11T00:00:00.000Z,260.85,22325.40,22511.00,22311.20,22486.95,199.80,30.30,230.55,260.85,9.85,-16.25
4,4,254.45,2024-03-07T00:00:00.000Z,314.10,22483.60,22519.60,22439.20,22498.05,80.40,59.65,247.95,314.10,-6.40,-3.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,3,173.05,2023-07-24T00:00:00.000Z,212.20,19663.65,19781.45,19663.65,19729.35,117.80,39.15,173.05,212.20,2.40,-34.10
169,4,215.80,2023-07-21T00:00:00.000Z,237.80,19772.00,19885.90,19709.10,19797.10,176.80,13.20,211.45,229.00,3.60,42.65
170,0,20.10,2023-07-20T00:00:00.000Z,95.10,19967.70,19989.90,19759.65,19831.10,230.25,74.90,15.80,95.00,0,0
171,1,94.65,2023-07-19T00:00:00.000Z,127.50,19839.55,19841.60,19730.65,19837.75,110.95,32.25,94.30,126.90,-0.35,8.45
172,2,133.40,2023-07-18T00:00:00.000Z,163.95,19744.35,19813.20,19692.45,19771.40,120.75,23.45,133.40,156.85,6.50,-93.40

## we will keep data till 12th march, because we have to predict for 12th march

In [60]:
# save the target column, i.e., 12th march's column
target_column = df_dropped.iloc[2]

# drop the excess columns
df_train = df_dropped.drop(df.index[:2])
df_train.reset_index(drop=True)
df_train

,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
2,2,198.55,2024-03-12T00:00:00.000Z,233.15,22335.65,22450.70,22261.40,22341.65,189.30,22.15,195.25,220.70,10.90,-67.40
3,3,230.55,2024-03-11T00:00:00.000Z,260.85,22325.40,22511.00,22311.20,22486.95,199.80,30.30,230.55,260.85,9.85,-16.25
4,4,254.45,2024-03-07T00:00:00.000Z,314.10,22483.60,22519.60,22439.20,22498.05,80.40,59.65,247.95,314.10,-6.40,-3.35
5,0,6.55,2024-03-07T00:00:00.000Z,118.00,22483.60,22519.60,22439.20,22498.05,80.40,111.45,4.65,118.00,0,0
6,1,125.55,2024-03-06T00:00:00.000Z,190.60,22484.55,22486.55,22227.55,22304.55,259.00,59.80,123.10,185.35,7.55,-13.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,3,173.05,2023-07-24T00:00:00.000Z,212.20,19663.65,19781.45,19663.65,19729.35,117.80,39.15,173.05,212.20,2.40,-34.10
169,4,215.80,2023-07-21T00:00:00.000Z,237.80,19772.00,19885.90,19709.10,19797.10,176.80,13.20,211.45,229.00,3.60,42.65
170,0,20.10,2023-07-20T00:00:00.000Z,95.10,19967.70,19989.90,19759.65,19831.10,230.25,74.90,15.80,95.00,0,0
171,1,94.65,2023-07-19T00:00:00.000Z,127.50,19839.55,19841.60,19730.65,19837.75,110.95,32.25,94.30,126.90,-0.35,8.45
172,2,133.40,2023-07-18T00:00:00.000Z,163.95,19744.35,19813.20,19692.45,19771.40,120.75,23.45,133.40,156.85,6.50,-93.40

In [59]:
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

def create_lstm_model(look_back, n_features):
  """Creates an LSTM model for time series forecasting.

  Args:
      look_back (int): Number of past time steps to consider for prediction.
      n_features (int): Number of features in the input data.

  Returns:
      keras.Model: Compiled LSTM model.
  """

  model = Sequential()
  model.add(LSTM(units=128, activation='relu', return_sequences=True, input_shape=(look_back, n_features)))
  model.add(LSTM(units=64, activation='relu', return_sequences=True))
  model.add(LSTM(units=32, activation='relu', return_sequences=True))
  model.add(LSTM(units=16, activation='relu', return_sequences=True))
  model.add(LSTM(units=8, activation='relu'))
  model.add(Dense(units=4))  # Output layer with 4 units for open, high, low, close
  model.compile(loss='mse', optimizer='adam')
  return model

def prepare_data(df, forecast_days=1, look_back=5):
  """Prepares data for LSTM model training.

  Args:
      df (pandas.DataFrame): DataFrame containing option straddle data.
      forecast_days (int, optional): Number of days to forecast. Defaults to 1.
      look_back (int, optional): Number of past time steps to consider for prediction.

  Returns:
      tuple: Tuple containing training and testing data (X_train, y_train, X_test, y_test).
  """

  # Handle missing values (replace with last valid non-NaN value)
  df.fillna(method='ffill', inplace=True)

  # Convert 'date' column to datetime format
  df['date'] = pd.to_datetime(df['date'])

  # Set 'date' as index for efficient time series analysis
  df.set_index('date', inplace=True)

  # Create separate NumPy arrays for features ('open', 'high', 'low', 'close') and target
  data = df[['open', 'high', 'low', 'close']].values
  n_features = 4

  # Split data into sequences for LSTM
  X, y = [], []
  for i in range(look_back, len(data)):
    X.append(data[i-look_back:i, :])
    y.append(data[i, :])  # Predict all four prices (open, high, low, close)

  # Split data into training and testing sets
  X_train, X_test = np.array(X[forecast_days:]), np.array(X[:forecast_days])
  y_train, y_test = np.array(y[:-forecast_days]), np.array(y[-forecast_days:])

  # Reshape input data for LSTM (samples, time steps, features)
  X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], n_features))
  X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], n_features))

  return X_train, y_train, X_test, y_test

def train_lstm_model(df, forecast_days=1, look_back=7, epochs=100):
  """Trains an LSTM model for time series forecasting.

  Args:
      df (pandas.DataFrame): DataFrame containing option straddle data.
      forecast_days (int, optional): Number of days to forecast. Defaults to 1.
      look_back (int, optional): Number of past time steps to consider for prediction. Defaults to 7.
      epochs (int, optional): Number of training epochs. Defaults to 100.

  Returns:
      keras.Model: Trained LSTM model.
  """

  X_train, y_train, X_test, y_test = prepare_data(df.copy(), forecast_days, look_back)
  model = create_lstm_model(look_back, 4)

  # Train the model
  model.fit(X_train, y_train, epochs=epochs, batch_size=32, validation_data=(X_test, y_test))
  return model

def predict_with_lstm(model, X_test):
  """Predicts future values using a trained LSTM model.

AttributeError: 'Series' object has no attribute 'type'